[package]
name = "sta"
version = "0.1.0"
authors = ["ins099 <alaminsaram92@gmail.com.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
